### PR TITLE
Docs: Updated CKFinder path.

### LINKED ISSUE #37: Docs: update CKFinder path
Docs demos should use new CKFinder location: `https://ckeditor.com/apps/ckfinder/3.4.5/`

### PR DESCRIPTION
**Pull request by vokiel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Updated CKFinder path to the new location under ckeditor.com domain. Closes #37.

---

### Additional information

Custom build with CORS fixes have been moved to `ckeditor.com/apps`, so it can be used anywhere in docs.

### CODE REVIEW

**Comment by Reinmar** [comment]
@pomek Please check whether it works with the CSP rules we have defined.

**Comment by Reinmar** [comment]
image

I actually think it won't work.

**Comment by vokiel** [comment]
Oh, forgot about the CSP. Although, on the ckeditor.com/docs/ it should work just fine due to `self` defined. To be available locally, the `https://ckesource.com/` should be replaced with `https://ckeditor.com/`.

**Comment by pomek** [comment]
I cannot load an image to the editor using CKFinder (in the manual test).

image

Everything works on `master`.

**Comment by pomek** [comment]
Same problem in the docs: `features/image-upload/ckfinder.html#full-integration`.

**Comment by vokiel** [comment]
That was a configuration issue on the server side (returning relative instead of absolute path). Fixed now.

**Pull request merged**
